version: '3.5'
services:
  # database layer
  postgres_database:
    container_name: lighthouse-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - common-net

#   nest:
#     container_name: lighthouse-backend
#     links:
#       - postgres_database
#     depends_on:
#       - postgres_database
#     build:
#       context: .
#     ports:
#       - 3000:3000
#     networks:
#       - common-net
volumes:
  db-data:
networks:
  common-net: {}
