version: '3.5'
services:
  # database layer
  # postgres_database:
  #   container_name: lighthouse-postgres
  #   image: postgres
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: lighthouse
  #     MYSQL_USER: backend_user
  #     MYSQL_PASSWORD: 123456
  #   expose:
  #     - 5432
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/var/lib/mysql
  #   networks:
  #     - common-net

  nest:
    container_name: lighthouse-backend
    # links:
    #   - postgres_database
    # depends_on:
    #   - postgres_database
    build:
      context: .
    ports:
      - 3000:3000
    # volumes:
      # - attachment-files:/usr/src/app/uploads
    networks:
      - common-net

volumes:
  postgres:
networks:
  common-net: {}
